### ISSUE TITLE
Main menu doesn´t launch

### ISSUE THREAD

**Issue by Paco8412** [tdewin/veeamhubrepo#4]
Hi Guys
first of all, my name is Francisco i hope every one is having a nice day

i'm new in all of this Github stuff and i,m helping a teammate with the instalation of the veeamhubrepo, we executed the wizard and everything seems to install ok

but at the moment we launch veeamhubrepo to get the main menu, it doesn't come up, and we get this output

---- sudo veeamhubrepo
Traceback (most recent call last):
  File "/usr/bin/veeamhubrepo", line 1045, in <module>
    main()
  File "/usr/bin/veeamhubrepo", line 1036, in main
    home(style="default")
  File "/usr/bin/veeamhubrepo", line 989, in home
    ln = ["Current IPv4: {}".format(",".join(myips()))]
  File "/usr/bin/veeamhubrepo", line 37, in myips
    for nifaddr in netifaces.ifaddresses(nif)[netifaces.AF_INET]:
KeyError: 2

i'm not a linux or python expert so i don't have any idea why is not working

is there any advise that you can give us... and sorry for the terrible english and for if this is not the correct place to ask for help

**Comment by poulpreben** [comment]
Hi Paco,

Can you please share what distro and version you are running, as well as the output of `ip addr`?

**Comment by Paco8412** [comment]
Hi poulpreben

sure, here is the info, by the way, i manage to "resolve the issue", I modified the code, i know is not the best or recommended solution, but it worked

I'm using Ubuntu Server 20.04 LTS, and here is the info, i'm using eno49 and eno50

1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
2: eno1: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN group default qlen 1000
    link/ether 94:18:82:6f:a8:80 brd ff:ff:ff:ff:ff:ff
3: eno2: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN group default qlen 1000
    link/ether 94:18:82:6f:a8:81 brd ff:ff:ff:ff:ff:ff
4: eno49: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
    link/ether 14:02:ec:88:81:9c brd ff:ff:ff:ff:ff:ff
    inet 10.152.112.31/24 brd 10.152.112.255 scope global eno49
       valid_lft forever preferred_lft forever
    inet6 fe80::1602:ecff:fe88:819c/64 scope link
       valid_lft forever preferred_lft forever
5: eno3: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN group default qlen 1000
    link/ether 94:18:82:6f:a8:82 brd ff:ff:ff:ff:ff:ff
6: eno4: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN group default qlen 1000
    link/ether 94:18:82:6f:a8:83 brd ff:ff:ff:ff:ff:ff
7: eno50: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
    link/ether 14:02:ec:88:81:9d brd ff:ff:ff:ff:ff:ff
    inet 10.152.112.32/26 brd 10.152.112.63 scope global eno50
       valid_lft forever preferred_lft forever
    inet6 fe80::1602:ecff:fe88:819d/64 scope link
       valid_lft forever preferred_lft forever

the solution that i applied was modify the "myips" function and hardcoded the Server IPs, after that the main menu worked

# creates a list of all ipv4 address
#def myips():
#    ipaddr = []
#    for nif in netifaces.interfaces():
#            if nif != 'lo':
#                        for nifaddr in netifaces.ifaddresses(nif)[netifaces.AF_INET]:
#                                        ipaddr.append(nifaddr['addr'])
#    return ipaddr

def myips():
 ipaddr = []
 ipaddr.append('10.152.112.31')
 ipaddr.append('10.152.112.32')
 return ipaddr

**Comment by tdewin** [comment]
are you sure you are running the latest version? I fixed this issues in the past (was in 0.3.1, should be fixed in 0.3.2)

https://github.com/tdewin/veeamhubrepo/commit/f2660e637715b62299d4e9f84ab01f9c0c5442b7

package : https://github.com/tdewin/veeamhubrepo/releases/download/v0.3.2/veeamhubrepo_noarch.deb

**Comment by Paco8412** [comment]
Hi tdewin
that is the problem, my team mate provided me with the link of the 0.3.1 versión

https://github.com/tdewin/veeamhubrepo/releases/download/v0.3.1/veeamhubrepo_noarch.deb

**Comment by tdewin** [comment]
Solved!
