### ISSUE TITLE
No Issue - Just a question

### ISSUE THREAD

**Issue by tomstadrew** [tdewin/veeamhubrepo#8]
Thanks for a great script!!

- Is the script sae to run on all Ubuntu 20.04 LTS releases and patch levels? We would like to keep upr systems updated inside the same release.
- Is there a plan to try the script out on newer LTS releases?
 
Kind Regards
Tomas

**Comment by tdewin** [comment]
So first of all, yes if I have some time, I would definitely like to support 22.04 LTS especially since there is now a direct patch

It should work on latest patches since it just run standardized ubuntu commands. If that is not the case let me know

**Comment by tomstadrew** [comment]
Thanks a lot for your answers!

Kind Regards
Tomas
________________________________
Från: tdewin ***@***.***>
Skickat: den 18 oktober 2022 09:23
Till: tdewin/veeamhubrepo ***@***.***>
Kopia: Tomas Ståhl ***@***.***>; Author ***@***.***>
Ämne: Re: [tdewin/veeamhubrepo] No Issue - Just a question (Issue #8)


So first of all, yes if I have some time, I would definitely like to support 22.04 LTS especially since there is now a direct patch

It should work on latest patches since it just run standardized ubuntu commands. If that is not the case let me know

**Comment by tdewin** [comment]
Just did a smoke test on 22.04 LTS with v12 (and latest patching at the moment of writing). All seems to work just fine with 0.3.2
