### ISSUE TITLE
Ubuntu 22.04 LTS Supported?

### ISSUE THREAD

**Issue by illumiN8i** [tdewin/veeamhubrepo#9]
Does this support the newer Ubuntu 22.04 LTS or is it still required to use Ubuntu 20.04 LTS? I'm planning on using this script to deploy a hardened repository for the first time and want to future proof the LTS version if possible since 20.04 LTS support ends next year: https://ubuntu.com/about/release-cycle

**Comment by poulpreben** [comment]
I can confirm it works without issues on 22.04.
